SELECT CONCAT(NAME, '(', LEFT(OCCUPATION, 1), ')') FROM OCCUPATIONS ORDER BY NAME;

SELECT
    CASE
        WHEN COUNT(OCCUPATION) > 1 THEN CONCAT("There are a total of ", COUNT(OCCUPATION), " ", LOWER(OCCUPATION), "s.")
        ELSE CONCAT("There are a total of ", COUNT(OCCUPATION), " ", LOWER(OCCUPATION), ".")
    END
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION), OCCUPATION;
